.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> feat: add pr and issue templates

_contributors/avneesh.md, _data/contributors.yml
I have added myself as author! :D
=> add avneesh as author

_contributors/anishde12020.md, _data/contributors.yml
=> Add Anish De to contributors list

_drafts/supabase-database-next.md
=> fix: commit the required changes

_data/contributors.yml, _scripts/validatecontributors.py
=> Test valid-contributors gh-action

_data/contributors.yml, _scripts/validate-contributors.py
=> Test validate contributors script

_contributors/sahilpabale.md, _data/contributors.yml
=> added sahilpabale to contributors

.github/ISSUE_TEMPLATE/submission_request.md
=> fix(issue-templates): fixed broken link for submission request article

_contributors/karthikpariti.md, _data/contributors.yml
=> Add karthik as contributor

_data/announcement.yml, _pages/contact.md, _pages/contribute.md, _pages/privacy-policy.md, _pages/terms.md
#41 - Fix for the Discord links to new discord sub domain
I just changed all discord links to new subdomain in almost 5 files.
=> Replace all discord links to new subdomain

_contributors/MaheshtheDev.md, _data/announcement.yml, _data/contributors.yml, _pages/contact.md, _pages/contribute.md, _pages/privacy-policy.md, _pages/terms.md
I added my profile as a author at GeniusBlog
=> Add MaheshtheDev author to GeniusBlog

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/submission_request.md
I have commented out descriptions in issue templates.
Also, a submission request issue label can be added and automatically added to any submission request issue (edit frontmatter). Person with perms to edit repo content needs to do this.
=> Improved Issue Templates

_scripts/validate-drafts.py
=> fix(scripts): fixed syntax error in validate-drafts script

_drafts/make-a-toast-with-html-css-and-js.md
=> chore(draft): make a toast with html css and js

_contributors/usman.md, _data/contributors.yml
Let me know if the avatar URL will work or not.
=> Add myself as a contributor

_contributors/Kira.md, _data/contributors.yml
=> feat: add kira as a contributor

_drafts/how-to-build-a-rest-api-using-nodejs.md
Created  a draft for the ["How to build a REST API using NodeJS"](https://kirablog.hashnode.dev/rest-api-using-nodejs) blog
=> feat: add "How to build a REST API using NodeJS" blog

_contributors/adityasingh.md, _data/contributors.yml, _drafts/6-free-websites-to-learn-web3.md
=> Create: 6-free-website-to-learn-web3.md

_drafts/intro-to-graphql-with-node-and-typescript.md
=> Add Intro to GraphQL with Node.js and TypeScript Post

_drafts/five-projects-to-become-better-at-webdev.md
[Submission Issue](https://github.com/genicsblog/genicsblog.github.io/issues/71)
=> Added "5 projects you can make to become a better webdev" blog post

_drafts/underrated-html-tags-every-webdev-should-know.md
https://github.com/genicsblog/genicsblog.com/issues/95
=> Created the draft for "15 less-known and underrated HTML tags for webdevs"

_drafts/How-to-build-a-blog-using-Remix-and-MDX.md
- #94 
Add new blog post on "How to build a blog using Remix and MDX"
=> docs: add new blog post

_config.yml
Add ReCaptcha instead of Javascript-based custom captcha.
=> Add recaptcha

_drafts/privacy-friendly-website-analytics-with-umami-and-nextjs.md
=> Add Umami analytics with NextJS

_drafts/solidity-quickstart-0.md
- Closes #113 
Added new article, "Solidity Quickstart [0]"
=> feat: add new article, "Solidity Quickstart [0]"

_drafts/building-clis-with-react-ink.md
=> new post: "🧑‍💻 Building CLIs with React Ink"

_drafts/the-javascript-cheatsheet-for-new-coders.md
Added escape characters to special characters that changed the md formatting.
Example of changes:
The cover image did not load for me
=> Fixed issues with special characters

_drafts/5-chrome-keyboard-shortcuts-to-boost-your-productivity
=> Add 5 Chrome Keyboard Shortcuts to boost your productivity

_data/authors.yml
Hey there, myself Arshroop I am looking forward to contribute. Please accept my PR.
=> Adding user profile(Arshroop Singh)

.github/workflows/publish-site.yml, Dockerfile
Please join [our discord server](https://discord.genicsblog.com/) to host discussions related to articles. Thanks.
=> Remove comments functionality

.github/workflows/publish-site.yml
Workflow dispatch didn't work correctly.
=> Fix workflow

_data/authors.yml
=> Add my twitter

_drafts/genics-log-2.md
Mostly spelling and grammar fixes.
=> Review/updates of genics-log-2.md

_drafts/test.md, _posts/genics-log/2022-02-10-genics-log-1.md, _posts/genics-log/2022-06-17-genics-log-2.md, _posts/gouravkhunger/2021-02-09-how-to-make-efficient-content-applications-in-android.md, _posts/gouravkhunger/2021-05-23-introducing-quotes-app.md, _posts/gouravkhunger/2021-08-31-introducing-jekyllex-android-app.md, _posts/gouravkhunger/2021-09-14-3-years-of-blogging.md, _posts/gouravkhunger/2021-09-16-how-to-create-your-first-android-app-using-android-studio.md, _posts/gouravkhunger/2021-09-22-android-application-fundamentals.md, _posts/gouravkhunger/2021-09-26-authentication-in-android-app-with-auth0.md, _posts/gouravkhunger/2021-09-26-trying-out-nextjs.md, _posts/gouravkhunger/2021-11-07-how-to-support-multiple-fonts-in-an-android-app.md, _posts/gouravkhunger/2022-01-31-next-generation-hello-world-program.md, _posts/gouravkhunger/2022-03-17-8-ways-to-keep-your-heroku-app-awake.md, _posts/gouravkhunger/2022-04-03-how-to-create-a-pull-request-in-github-correctly.md, _posts/gouravkhunger/2022-04-10-adding-multiple-authors-to-a-jekyll-blog-got-easier.md, _posts/gouravkhunger/2022-04-24-pagination-in-android-room-database-using-the-paging-3-library.md, dev.sh
This PR converts certain links in current articles to the newly added [linkpreview components](https://github.com/genicsblog/theme-files/pull/55) which look much cleaner!
=> Use newer link preview components

.github/workflows/publish-site.yml
Fixes #158 
Add a step to cache `.jekyll-cache` folder in site publish workflow. This will significantly improve build times.
=> Cache `.jekyll-cache` folder in CI

README.md
closes #106 
added a proper description of the site, a repo structure, contributing docs in the readme, and improved the local setup guide
=> docs: :memo: update readme with more info
